Better/worse badge labels & sort order fix
nycehs/ehs-data-portal-frontend-temp pull request #1
Opened 2021-07-16 16:18 UTC by mmontesanonyc

@grantpezeshki - applying the fixes we did in Wednesday's meeting. Mind taking a look and merging if all looks well?

2021-07-16 18:13 UTC, grantpezeshki requested changes
Looks great so far but to complete issue fix must update CSS also

2021-07-16 18:13 UTC, grantpezeshki commented on themes/dohmh/layouts/partials/report_indicator.html
> +      {{ if eq (string .ind.data_value_rank) "1" }}<span class="better">Worse</span>
These changes look great but I think we need to also update the CSS, so that all is consistent: in other words, we should not have the 'better' data need the 'worse' css class. This may mean reversing the css class labels, then updating the report partial to back like it was... Can you add that in? once done I'm happy to merge these changes.

2021-07-19 15:22 UTC, mmontesanonyc commented
@grantpezeshki - changed the CSS classes to match the label text, too.

2021-07-19 22:20 UTC, grantpezeshki approved these changes
These look good - did the SCSS under resources/_gen/assets/scss/scss/theme.scss_f300667da4f5b5f84e1a9e0702b2fdde.content generate automatically on build, or did all those happen with find/replace or something?  I'm assuming they get generated on build. anyhow good to merge. Thanks

2021-07-19 22:21 UTC, merged